version: '3.5'

services:

  task-backend-service:
    environment:
        - GOOGLE_APPLICATION_CREDENTIALS=keys/key.json
    build:
      context: ./task-backend-service
      args:
        env_file: local.env
    # command: python main.py
    ports:
      - "9098:9098"
      

    